

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.MessageFormat;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JTable;

import net.proteanit.sql.DbUtils;
import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.print.PrinterException;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author NirmalGds
 */
public class stock_count_full_report extends javax.swing.JFrame {

    /**
     * Creates new form stock_count_full_report
     */
    public static void tabledata()
    {
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/gdlashmi?useSSL=false","root","");
            PreparedStatement pst = con.prepareStatement("select location.name as `Location Name`,count(stock.location) as `Present Count`, location.count AS `Max Count`,GREATEST(location.count-count(stock.location),0) as `Absent Count` FROM location LEFT OUTER JOIN (SELECT * FROM stocklist Where flag = 1) AS stock ON location.name = stock.location GROUP BY location.name ORDER BY location.name");
            PreparedStatement pst1= con.prepareStatement("SELECT SUM(absent) FROM (SELECT location.name,count(stock.location),location.count,location.count - count(stock.location) as absent  FROM location LEFT OUTER JOIN (SELECT * FROM stocklist WHERE flag = 1) AS stock ON location.name = stock.location WHERE location.name IN (\"TRAY 01\",\"TRAY 02\",\"TRAY 03\",\"TRAY 06\",\"TRAY 07\",\"TRAY 08\",\"TRAY 09\",\"TRAY 10\",\"TRAY 11\",\"TRAY 12\",\"TRAY 13\",\"TRAY 14\",\"TRAY 15\",\"TRAY 16\",\"TRAY 17\",\"TRAY 20\",\"TRAY 23\",\"TRAY 24\",\"TRAY 25\",\"TRAY 25\",\"TRAY 26\",\"TRAY 27\",\"TRAY 28\",\"TRAY 29\",\"TRAY 30\",\"TRAY 31\",\"TRAY 32\",\"TRAY 33\",\"TRAY 34\",\"TRAY 35\",\"TRAY 34\",\"TRAY 35\",\"TRAY 36\",\"TRAY 37\",\"TRAY 38\") GROUP BY location.name) AS processed");
            ResultSet rs = pst.executeQuery();
            ResultSet rs1= pst1.executeQuery();
            if(rs != null)
            {
                jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            }
            if(rs1.next())
            {
            	jTextField1.setText(String.valueOf(rs1.getInt(1))+ " Nos.");
            }
        }catch(Exception e)
        {
            e.printStackTrace();
        }
    }
    public stock_count_full_report() {
    	setTitle("ITEMIZATION - Stock Count Full Report");
    	setIconImage(Toolkit.getDefaultToolkit().getImage(stock_count_full_report.class.getResource("/images/itemization_logo.png")));
    	getContentPane().setBackground(new Color(176, 224, 230));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane1.setEnabled(false);
        jTable1 = new javax.swing.JTable();
        jTable1.setEnabled(false);
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Over All Absent Count");

        jTextField1.setEditable(false);

        jToggleButton1.setText("Print");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jToggleButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jToggleButton1KeyPressed(evt);
            }
        });

        jToggleButton2.setText("Back");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        jToggleButton2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jToggleButton2KeyPressed(evt);
            }
        });

        jToggleButton3.setText("Home");
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });
        jToggleButton3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jToggleButton3KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(jToggleButton1)
                .addGap(83, 83, 83)
                .addComponent(jToggleButton2)
                .addGap(81, 81, 81)
                .addComponent(jToggleButton3)
                .addContainerGap(171, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton3)
                    .addComponent(jToggleButton2)
                    .addComponent(jToggleButton1))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>                        

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                               
        HomePage.main(null);
        this.dispose();
    }                                              

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                               
    	MessageFormat header = new MessageFormat("Stock Count Full Report");
    	MessageFormat footer = new MessageFormat("Page{0,number,integer}");
        try {
            jTable1.print(JTable.PrintMode.FIT_WIDTH, header, footer);
        } catch (PrinterException ex) {
            Logger.getLogger(instocklist.class.getName()).log(Level.SEVERE, null, ex);
        }    	
    }                                              

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                               
    	stock_count_navi.main(null);
    	this.dispose();
    }                                              

    private void jToggleButton1KeyPressed(java.awt.event.KeyEvent evt) {                                          
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
        	MessageFormat header = new MessageFormat("Stock Count Full Report");
        	MessageFormat footer = new MessageFormat("Page{0,number,integer}");
            try {
                jTable1.print(JTable.PrintMode.FIT_WIDTH, header, footer);
            } catch (PrinterException ex) {
                Logger.getLogger(instocklist.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else if(evt.getKeyCode() == KeyEvent.VK_BACK_SPACE)
        {
        	stock_count_navi.main(null);
        	this.dispose();
        }
    }                                         

    private void jToggleButton2KeyPressed(java.awt.event.KeyEvent evt) {                                          
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
        	stock_count_navi.main(null);
        	this.dispose();
        }
        else if(evt.getKeyCode() == KeyEvent.VK_BACK_SPACE)
        {
        	stock_count_navi.main(null);
        	this.dispose();
        }
    }                                         

    private void jToggleButton3KeyPressed(java.awt.event.KeyEvent evt) {                                          
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
        	HomePage.main(null);
            this.dispose();
        }else if(evt.getKeyCode() == KeyEvent.VK_BACK_SPACE)
        {
        	stock_count_navi.main(null);
        	this.dispose();
        }
    }                                         

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(stock_count_full_report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(stock_count_full_report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(stock_count_full_report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(stock_count_full_report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new stock_count_full_report().setVisible(true);
                tabledata();
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTable jTable1;
    private static javax.swing.JTextField jTextField1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    // End of variables declaration                   
}
